### ISSUE TITLE
Online statistical analysis tool not working

### ISSUE THREAD

**Issue by ghost** [jasonstrimpel/datasciencecoursera#1]
Your statistical analysis tool http://finance.jasonstrimpel.com/statistical-analysis/ is not working. Is it depricated?

**Comment by kbh4r4th** [comment]
@potholiday Are you from India & doing trading using JStock?

**Comment by ghost** [comment]
@b6arat6  yep why ?

**Comment by kbh4r4th** [comment]
@potholiday i am also from india & use jstock. just though to connect with you about trading strategies/extending jstock. are you interested in discussing?

**Comment by ghost** [comment]
@b6arat6 sorry but at this time I am not looking to partner with any one. I myself is in my early stages of stock trading and trying  to hone my own trading skills. I wish you a happy and prosperous trading and good luck.

**Comment by kbh4r4th** [comment]
@potholiday thats ok but lets have a small discussion about trading using jstock with its indicators & patterns, if you agree - we could share the indicators each other as well. Can we be connected in facebook so that we could discuss when you are ready?

**Comment by jasonstrimpel** [comment]
Just saw this, will take a look.

**Comment by jasonstrimpel** [comment]
And take your conversation off my repo.

**Comment by ghost** [comment]
@jasonstrimpel did you able to fix the problem. Your web app was real help?
